language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO='django>=1.11,<2'
  - DJANGO='django>=2,<2.1'
  - DJANGO='--pre django'
matrix:
  exclude:
   - python: "2.7"
     env: DJANGO='django>=2,<2.1'
   - python: "3.4"
     env: DJANGO='--pre django'
  allow_failures:
    - env: DJANGO='--pre django'
  fast_finish: true
install:
  - psql -c 'CREATE DATABASE orderable' -U postgres;
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -e .
script: "make test"
notifications:
  email: false
before_install:
  pip install codecov
after_success:
  codecov
