language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO='django>=1.8,<1.9'
  - DJANGO='django>=1.9,<1.10'
  - DJANGO='django>=1.10,<1.11'
  - DJANGO='--pre django'
matrix:
  exclude:
   - python: "3.3"
     env: DJANGO='django>=1.9,<1.10'
   - python: "3.3"
     env: DJANGO='django>=1.10,<1.11'
   - python: "3.3"
     env: DJANGO='--pre django'
  allow_failures:
    - env: DJANGO='--pre django'
  fast_finish: true
install:
  - psql -c 'CREATE DATABASE orderable' -U postgres;
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -e .
script: "make test"
notifications:
  email: false
before_install:
  pip install codecov
after_success:
  codecov
